Repository TechnicienDeSurface/Symfony-CongeFacile, pull requests merged in 2025-05, with the labels that each got.

#190 Modifs - Traductions - codes/Alertes
  src/Form/ChangePasswordFormType.php
  templates/reset_password/reset.html.twig
Labels: enhancement

#192 UPDATE - Message d'erreur quand aucune email n'est présente dans la b…
  src/Controller/ResetPasswordController.php
  src/Controller/SecurityController.php
  src/Entity/User.php
  templates/reset_password/request.html.twig
  templates/security/login.html.twig
Labels: 1h

#198 Heddy/corrections formulaires details
  src/Controller/Manager/Admin/JobController.php
  src/Controller/Manager/Admin/ManagementServiceController.php
  src/Controller/Manager/Admin/TypeOfRequestController.php
  src/Form/AddJobForm.php
  src/Form/DepartmentType.php
  src/Form/EditJobForm.php
  src/Form/RequestTypeForm.php
  src/Repository/PersonRepository.php
  src/Repository/RequestRepository.php
  templates/manager/admin/job/add_job.html.twig
  templates/manager/admin/job/detail_job.html.twig
  templates/manager/admin/management-service/add_management_service.html.twig
  templates/manager/admin/management-service/detail_management_service.html.twig
  templates/manager/admin/management-service/management_service.html.twig
  templates/manager/admin/type-of-request/detail_type_of_request.html.twig
Labels: 2h

#199 UPDATE - Front side bar avec variable page.
  src/Controller/HomeController.php
  src/Controller/Manager/Admin/JobController.php
  src/Controller/Manager/Admin/ManagementServiceController.php
  src/Controller/Manager/Admin/ManagerController.php
  src/Controller/Manager/PreferenceController.php
  src/Controller/Manager/RequestController.php
  src/Controller/Manager/TeamController.php
  src/Controller/SecurityController.php
  src/Controller/collaborator/RequestController.php
  templates/layout/menu/_sidebar.html.twig
  templates/manager/admin/job/detail_job.html.twig
  templates/manager/admin/job/job.html.twig
  templates/manager/admin/management-service/management_service.html.twig
  templates/manager/admin/manager/detail_manager.html.twig
  templates/manager/admin/manager/manager.html.twig
  templates/manager/admin/type-of-request/type_of_request.html.twig
  templates/manager/detail_history_request.html.twig
  templates/manager/detail_team.html.twig
Labels: bug, 1h

#196 Update reset.html
  templates/reset_password/reset.html.twig
Labels: enhancement

#203 Ajout de vérifications à mes informations collaborateurs currentPassw…
  src/Controller/collaborator/InformationController.php
Labels: 30m, back

#211 Heddy/corrections administrations services postes
  src/Controller/Manager/Admin/JobController.php
  src/Controller/Manager/Admin/ManagementServiceController.php
  src/Controller/Manager/Admin/TypeOfRequestController.php
  src/Form/DepartmentType.php
  src/Form/EditJobForm.php
  src/Repository/PersonRepository.php
  templates/manager/admin/job/detail_job.html.twig
Labels: 1h, back

#213 UPDATE - Fonctionnement opérationnel du téléchargement du justificatif
  config/services.yaml
  public/assets/uploads/C-11-La-protection-du-salarie-6820b193adb12-6820b4c37bf7e.pdf
  public/assets/uploads/C-11-La-protection-du-salarie-6820b193adb12.pdf
  src/Controller/Manager/RequestController.php
  src/Controller/collaborator/RequestController.php
  src/Form/RequestType.php
  templates/collaborator/new_request.html.twig
  templates/manager/detail_history_request.html.twig
  templates/manager/detail_request_pending.html.twig
Labels: bug, 2h
