Repository TechnicienDeSurface/Symfony-CongeFacile, pull requests merged in 2025-03, with the labels that each got.

#93 ADRIEN - Création de la récupération/filtre des membres d'équipe dans manager
  composer.json
  composer.lock
  config/bundles.php
  src/Controller/HomeController.php
  src/Controller/Manager/TeamController.php
  src/Repository/PersonRepository.php
  symfony.lock
  templates/authentification/form_mdp.html.twig
  templates/layout/manager/_sidebar.html.twig
Labels: 1h

#96 CREATE - Création de mot de passe oublié, mail envoyé, amélioration front de la slide bar
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  config/packages/security.yaml
  src/Controller/HomeController.php
  src/Controller/ResetPasswordController.php
  src/Controller/SecurityController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/authentification/form_mdp.html.twig
  templates/default/index.html.twig
  templates/layout/menu/_sidebar.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
Labels: 4h

#98 Corrections JobController + InformationType + Relation manager + vari…
  src/Controller/HomeController.php
  src/Controller/Manager/Admin/JobController.php
  src/Entity/Person.php
  src/Form/InformationFormType.php
  templates/home/home.html.twig
Labels: enhancement

#99 Front administration service
  templates/manager/admin/management-service/management_service.html.twig
Labels: enhancement

#100 Màj composer + ManagerController
  composer.lock
  src/Controller/Manager/Admin/ManagerController.php
Labels: enhancement

#107 CREATE - Création du FRONT et BACK du module statistique
  public/assets/css/style.css
  src/Controller/Manager/Admin/ManagerController.php
  src/Controller/Manager/StatisticController.php
  src/Form/UserType.php
  templates/base.html.twig
  templates/layout/menu/_sidebar.html.twig
  templates/manager/statistic.html.twig
  templates/reset_password/email.html.twig
  templates/security/login.html.twig
Labels: 4h

#109 Front - Collaborateur - Détails d'une demande
  templates/collaborateur/detail_request.html.twig
Labels: intégration

#108 Intégration formulaire demande de congé
  src/Form/RequestType.php
  templates/collaborateur/new_request.html.twig
Labels: 2h

#112 Corrections des retours :
  src/Controller/Collaborateur/RequestController.php
  src/Controller/RegistrationController.php
  src/Entity/Department.php
  src/Entity/Person.php
  src/Entity/User.php
  src/Form/RequestType.php
  src/Repository/PersonRepository.php
Labels: 30m

#114 UPDATE - Continuation du back pour manager mon équipe.
  src/Controller/Manager/TeamController.php
  src/Entity/Person.php
  src/Entity/User.php
  src/Repository/PersonRepository.php
  templates/layout/menu/_sidebar.html.twig
  templates/manager/team.html.twig
Labels: 3h

#117 UPDATE - Finalisation de la page de création mes informations Manager.
  config/packages/framework.yaml
  src/Controller/ErrorController.php
  src/Controller/Manager/Admin/JobController.php
  src/Controller/Manager/InformationController.php
  src/Entity/Person.php
  src/Entity/User.php
  src/Form/InformationFormType.php
  src/Form/MotDePasseType.php
  templates/manager/information.html.twig
  templates/manager/team.html.twig
Labels: 3h

#119 UPDATE - Adrien/back administration type de demande
  src/Controller/Manager/Admin/TypeOfRequestController.php
  src/Controller/Manager/TeamController.php
  src/Entity/Request.php
  src/Entity/RequestType.php
  src/Form/FilterAdminDemandeFormType.php
  src/Form/FilterManagerTeamFormType.php
  src/Form/RequestTypeForm.php
  src/Repository/PersonRepository.php
  src/Repository/RequestTypeRepository.php
  templates/manager/admin/type-of-request/detail_type_of_request.html.twig
  templates/manager/admin/type-of-request/type_of_request.html.twig
  templates/manager/team.html.twig
Labels: 3h

#120 CREATE - Adrien/filtre administration poste
  src/Controller/Manager/Admin/JobController.php
  src/Entity/Person.php
  src/Entity/Position.php
  src/Repository/PositionRepository.php
  templates/manager/admin/job/job.html.twig
Labels: 3h

#122 Ajout : Front : Manager - Mon Equipe - Détails
  templates/manager/detail_team.html.twig
Labels: enhancement, intégration

#123 UPDATE - Heddy/back mes preferences alerte conge collaborateur
  .env
  composer.json
  composer.lock
  config/packages/mailer.yaml
  config/packages/messenger.yaml
  config/services.yaml
  scheduler.php
  src/Controller/TestMailController.php
  src/Controller/collaborator/PreferenceController.php
  src/Form/PreferenceType.php
  src/Service/MailerService.php
  symfony.lock
  templates/base.html.twig
  templates/collaborateur/preference.html.twig
  templates/layout/menu/_sidebar.html.twig
  templates/test_mail/index.html.twig
  templates/user/index.html.twig
Labels: 4h

#125 Ajout : Front - Administration - Directions/Services
  templates/manager/admin/management-service/management_service.html.twig
Labels: enhancement, intégration

#126 Ajout : Front-Administration-Direction/Service_Details/Modifs
  templates/manager/admin/management-service/detail_management_service.html.twig
Labels: enhancement, intégration
