Repository TechnicienDeSurface/Symfony-CongeFacile, pull requests merged in 2025-04, with the labels that each got.

#127 Intégration : Front - Manager - Consulter une Demande
  templates/manager/request_pending.html.twig
Labels: enhancement, intégration

#128 Heddy/ajout verifications rendu1
  config/services.yaml
  public/assets/js/ViewPassword.js
  public/assets/js/viewPasswordCollaborateur.js
  src/Controller/Manager/Admin/JobController.php
  src/Controller/collaborator/InformationController.php
  src/Controller/collaborator/RequestController.php
  src/Form/InformationFormType.php
  src/Form/MotDePasseType.php
  src/Form/RequestType.php
  templates/collaborator/information.html.twig
  templates/collaborator/new_request.html.twig
  templates/home/home.html.twig
  templates/layout/_addFlash.html.twig
  templates/layout/menu/_sidebar.html.twig
  templates/manager/admin/manager/manager.html.twig
Labels: help wanted, 4h, intégration, back

#129 Intégration : Front - Manager - Mes Préférences
  templates/manager/preference.html.twig
Labels: enhancement, intégration

#131 Front - Refonte header
  templates/layout/menu/_header.html.twig
Labels: enhancement, intégration

#132 Intégration - Front - Manager - Détails consulter une demande
  templates/manager/detail_request_pending.html.twig
Labels: enhancement, intégration

#134 Intégration - Manager - Demandes en attente
  templates/manager/request_pending.html.twig
Labels: enhancement, intégration

#136 Intégration - Administration - Directions/Services - Détails/Ajout
  templates/manager/admin/management-service/add_management_service.html.twig
Labels: enhancement, intégration

#139 Intégration - Administration - Manager - Ajout d'un manager
  templates/manager/admin/manager/add_manager.html.twig
Labels: enhancement, intégration

#141 Modifications sur Admin/Manager - Ajout Type de demandes
  templates/manager/admin/type-of-request/add_type_of_request.html.twig
Labels: enhancement

#142 CREATE - Adrien/historique demande manager et collaborateur
  src/Controller/Manager/RequestController.php
  src/Controller/collaborator/RequestController.php
  src/Entity/Request.php
  src/Form/FilterManagerTeamFormType.php
  src/Form/FilterRequestHistoryFormType.php
  src/Repository/PersonRepository.php
  src/Repository/RequestRepository.php
  templates/collaborator/request_history.html.twig
  templates/layout/menu/_sidebar.html.twig
  templates/manager/history_request.html.twig
Labels: 4h

#144 Heddy/vérifications corrections rendu2
  composer.json
  composer.lock
  src/Controller/Manager/Admin/JobController.php
  src/Controller/Manager/Admin/ManagerController.php
  src/Controller/Manager/RequestController.php
  src/Entity/Request.php
  src/Form/FilterHistoRequestType.php
  src/Form/FilterManagerHistoDemandeType.php
  src/Form/ManagerType.php
  src/Repository/DepartmentRepository.php
  src/Repository/PositionRepository.php
  src/Repository/RequestRepository.php
  templates/manager/admin/management-service/management_service.html.twig
  templates/manager/admin/manager/add_manager.html.twig
  templates/manager/admin/manager/detail_manager.html.twig
  templates/manager/admin/manager/manager.html.twig
  templates/manager/admin/type-of-request/type_of_request.html.twig
  templates/manager/history_request.html.twig
Labels: bug, 4h, intégration, back

#151 UPDATE - Fix de certains bug.
  src/Controller/Manager/RequestController.php
  src/Controller/Manager/TeamController.php
  src/DataFixtures/ManagerIdFixtures.php
  src/DataFixtures/PersonFixtures.php
  templates/layout/menu/_sidebar.html.twig
  templates/manager/history_request.html.twig
  templates/manager/request_pending.html.twig
Labels: bug

#150 Heddy/retour sprint1
  .vs/ProjectSettings.json
  .vs/Symfony-CongeFacile/FileContentIndex/e13badd2-b597-41d9-92e6-99ca9501883e.vsidx
  .vs/Symfony-CongeFacile/v17/.wsuo
  .vs/Symfony-CongeFacile/v17/DocumentLayout.json
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  src/Controller/collaborator/RequestController.php
  src/Form/RequestType.php
  templates/collaborator/new_request.html.twig
Labels: bug

#152 Back-Admin-Direction/Service
  src/Controller/Manager/Admin/ManagementServiceController.php
  templates/manager/admin/management-service/detail_management_service.html.twig
  templates/manager/admin/management-service/management_service.html.twig
Labels: enhancement, infra, back

#154 Front-Admin-Details_type_demande
  templates/manager/admin/type-of-request/detail_type_of_request.html.twig
  templates/manager/detail_team.html.twig
Labels: enhancement, intégration, back

#157 Back - Update - Ajout Direction_Service
  src/Controller/Manager/Admin/ManagementServiceController.php
  templates/manager/admin/management-service/add_management_service.html.twig
Labels: enhancement, back

#158 Back - Admin - Direction/Service - Améliorations
  templates/manager/admin/management-service/add_management_service.html.twig
  templates/manager/admin/management-service/detail_management_service.html.twig
Labels: enhancement, intégration, back

#159 Adrien/pagination manager
  src/Controller/Manager/Admin/JobController.php
  src/Controller/Manager/Admin/ManagerController.php
  src/Controller/Manager/Admin/TypeOfRequestController.php
  src/Controller/Manager/RequestController.php
  src/Repository/UserRepository.php
  templates/manager/admin/manager/manager.html.twig
  templates/manager/history_request.html.twig
  templates/manager/team.html.twig
Labels: bug, 2h

#165 Back - Admin - Direction/Services - Améliorations
  src/Controller/Manager/Admin/ManagementServiceController.php
  src/Form/DepartmentType.php
  templates/manager/admin/management-service/detail_management_service.html.twig
Labels: enhancement, infra, back

#166 UPDATE - Correctif total pour type de demande dans l'administration.
  src/Controller/Manager/Admin/JobController.php
  src/Controller/Manager/Admin/ManagementServiceController.php
  src/Controller/Manager/Admin/ManagerController.php
  src/Controller/Manager/Admin/TypeOfRequestController.php
  src/Entity/RequestType.php
  src/Form/RequestTypeForm.php
  templates/manager/admin/job/add_job.html.twig
  templates/manager/admin/job/job.html.twig
  templates/manager/admin/management-service/detail_management_service.html.twig
  templates/manager/admin/management-service/management_service.html.twig
  templates/manager/admin/manager/manager.html.twig
  templates/manager/admin/type-of-request/add_type_of_request.html.twig
  templates/manager/admin/type-of-request/detail_type_of_request.html.twig
  templates/manager/admin/type-of-request/type_of_request.html.twig
Labels: bug, 4h

#173 UPDATE - Type de demande et Poste erreur et fix du bug sur poste et type de demande.
  src/Controller/Manager/Admin/JobController.php
  src/Controller/Manager/Admin/TypeOfRequestController.php
  src/Entity/Position.php
  src/Form/EditJobForm.php
  templates/manager/admin/job/add_job.html.twig
  templates/manager/admin/job/detail_job.html.twig
  templates/manager/admin/type-of-request/detail_type_of_request.html.twig
Labels: bug, 1h

#175 UPDATE - Ajout des restrictions.
  src/Controller/Manager/Admin/JobController.php
  src/Controller/Manager/Admin/ManagementServiceController.php
  src/Controller/Manager/Admin/ManagerController.php
  src/Controller/Manager/Admin/TypeOfRequestController.php
  src/Controller/Manager/InformationController.php
  src/Controller/Manager/PreferenceController.php
  src/Controller/Manager/RequestController.php
  src/Controller/Manager/StatisticController.php
  src/Controller/Manager/TeamController.php
  src/Controller/RegistrationController.php
  src/Controller/collaborator/InformationController.php
  src/Controller/collaborator/PreferenceController.php
  src/Controller/collaborator/RequestController.php
Labels: 1h

#176 FInalisation demande en attente + détail
  src/Controller/Manager/RequestController.php
  src/Form/RequestStatusFormType.php
  templates/manager/detail_request_pending.html.twig
  templates/manager/request_pending.html.twig
Labels: 4h
